name: Actions CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Enable KVM group perms
        run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm

      - name: Install VM
        run: |
          set -x
          sudo snap install multipass
          multipass find
          multipass launch docker --name ubuntu-vm

      - name: Show VM and and enviroments variables
        run:  |
          export
          multipass exec ubuntu-vm -- lsb_release -a
          multipass info

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: multipass/ubuntu-vm

      - name: Run OpenWrt
        timeout-minutes: 10
        run: |
          multipass exec ubuntu-vm -- docker stop portainer # by default portainer is running at port 9000. But we need port 9000
          multipass exec ubuntu-vm -- sudo apt install python3-pip python-is-python3
          #multipass exec ubuntu-vm -- wget https://raw.githubusercontent.com/AlbrechtL/ci-playground/master/docker-compose.yml
          #multipass exec ubuntu-vm -- docker compose up 
          multipass exec ubuntu-vm -- pip install -r ubuntu-vm/test/requirements.txt
          