name: Actions CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: SBOM generation
    runs-on: ubuntu-latest
    
    steps:
      #- name: Enable KVM group perms
      #  run: |
      #      echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
      #      sudo udevadm control --reload-rules
      #      sudo udevadm trigger --name-match=kvm

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate alpine SBOM
        uses: anchore/sbom-action@v0
        with:
          image: albrechtloh/openwrt-docker:latest
          upload-artifact: false
          format: cyclonedx-json
          artifact-name: alpine_sbom.json
          output-file: .

      - name: Prepare OpenWrt rootfs
        run: |
          # Run OpenWrt container for some time to install additional IPKs
          set +e # Enable that the next command can fail
          timeout --preserve-status 30 docker compose up
          set -e # Revert set +e

          # Get image from volume
          sudo find /var/lib/docker/volumes/
          IMAGE=$(sudo cat /var/lib/docker/volumes/ci-playground_data/_data/current_version)
          echo $IMAGE

          # Mount volume
          sudo mount /var/lib/docker/volumes/ci-playground_data/_data/$IMAGE /mnt

      - name: Generate OpenWrt SBOM
        uses: anchore/sbom-action@v0
        with:
          path: /mnt
          upload-artifact: false
          format: cyclonedx-json
          artifact-name: openwrt_sbom.json
          output-file: .
          
      - name: Archive artifacts (SBOMs)
        uses: actions/upload-artifact@v4
        with:
          name: SBOM
          path: *.json
          if-no-files-found: error