name: Actions CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Enable KVM group perms
        run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm

      - name: Install VM
        run: |
          set -x
          sudo snap install multipass
          sudo chmod a+w /var/snap/multipass/common/multipass_socket # Fix 'multipass socket access denied'
          multipass find
          multipass launch docker --name ubuntu-vm
          multipass mount $GITHUB_WORKSPACE ubuntu-vm

      - name: Show VM and and enviroments variables
        run:  |
          export
          multipass exec ubuntu-vm -- lsb_release -a
          multipass info

      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare VM
        run: |
          # By default portainer is running at port 9000. But we need port 9000
          multipass exec ubuntu-vm -- docker stop portainer

          # Install python
          multipass exec ubuntu-vm -- sudo apt-get -y install python3-pip python-is-python3

          # Install everthing for pytest
          multipass exec ubuntu-vm -- find .
          #multipass exec ubuntu-vm -- export PATH=$PATH:~/.local/bin # not working
          multipass exec ubuntu-vm -- pip install -r test/requirements.txt

      - name: Run tests
        #timeout-minutes: 10
        run: |
          # Run pytest
          multipass exec ubuntu-vm -- sh -c 'cd test/ && ~/.local/bin/pytest -v'

          