name: Actions CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable KVM group perms
        run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm

      - name: Install VM
        run: |
          set -x
          sudo snap install multipass
          sudo multipass find
          sudo multipass launch docker --name ubuntu-vm

      - name: Show VM
        run:  |
          sudo multipass exec ubuntu-vm -- lsb_release -a

      - name: Run OpenWrt
        timeout-minutes: 10
        run: |
          sudo multipass exec ubuntu-vm -- wget https://raw.githubusercontent.com/AlbrechtL/ci-playground/master/docker-compose.yml
          sudo multipass exec ubuntu-vm -- docker compose up 
          